all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_user: risng
      ansible_become: true
      ansible_become_password: "iron"
      ssh_user: risng
      ssh_user_home: /home/risng
      ansible_hostname: risng

    bootstrapvm:
      ansible_connection: local
      ip: 10.228.229.7
      ansible_user: risng
      ansible_ssh_private_key_file: ~/.ssh/ansible_key_rsa.pub
      ansible_become: true
      ansible_become_password: "iron"

    

    slave:
      ansible_connection: local
      ip: 10.228.229.201
      ansible_user: risng
      ansible_ssh_private_key_file: ~/.ssh/ansible_key_rsa.pub
      ansible_become: true
      ansible_become_password: "iron"

  children:
    servers:
      hosts:
        baremetal1:
          ansible_host: 10.228.229.21
          ansible_user: risng
        baremetal2:
          ansible_host: 10.228.229.22
          ansible_user: risng
        baremetal3:
          ansible_host: 10.228.229.23
          ansible_user: risng


