all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_user: "{{ lookup('env', 'USER') }}"
      ansible_become: true
      ansible_become_password: "iron"
      ssh_user: "{{ lookup('env', 'USER') }}"
      ssh_user_home: "{{ '/home/' ~ (lookup('env', 'USER')) }}"
      ansible_hostname: "{{ lookup('env', 'USER') }}"

    bootstrapvm:
      ansible_connection: local
      ip: 10.228.229.7
      ansible_user: "{{ lookup('env', 'USER') }}"
      ansible_ssh_private_key_file: ~/.ssh/ansible_key_rsa.pub
      ansible_become: true
      ansible_become_password: "iron"

    

    slave:
      ansible_connection: local
      ip: 10.228.229.201
      ansible_user: "{{ lookup('env', 'USER') }}"
      ansible_ssh_private_key_file: ~/.ssh/ansible_key_rsa.pub
      ansible_become: true
      ansible_become_password: "iron"

  children:
    servers:
      hosts:
        baremetal1:
          ansible_host: 10.228.229.21
          ansible_user: "{{ lookup('env', 'USER') }}"
        baremetal2:
          ansible_host: 10.228.229.22
          ansible_user: "{{ lookup('env', 'USER') }}"
        baremetal3:
          ansible_host: 10.228.229.23
          ansible_user: "{{ lookup('env', 'USER') }}"


